pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/YOUR_USERNAME/expense-tracker.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                bat 'docker build -t expense-tracker .'
            }
        }

        stage('Run Container') {
            steps {
                bat 'docker run -d -p 3001:3000 expense-tracker'
            }
        }
    }
}
